/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.States.ClassLoadedState;
import GUI.States.InitState;
import GUI.States.LoadClassState;
import GUI.States.State;
import javax.swing.JLabel;

/**
 *
 * @author Sebastien
 */
public class Gui extends javax.swing.JFrame
{
    private State       state;
    private Mediator    mediator;
    
    public Gui()
    {
        initComponents();
        
        // Chargement du médiateur
        this.mediator = new Mediator(this);
        
        // Etat initial
        this.state = new InitState();
        this.state.doAction(mediator);
    }

    public JLabel getjLabelClassName()
    {
        return jLabelClassName;
    }

    public JLabel getjLabelATFD()
    {
        return jLabelATFD;
    }

    public JLabel getjLabelLinesCode()
    {
        return jLabelLinesCode;
    }

    public JLabel getjLabelMethodCount()
    {
        return jLabelMethodCount;
    }

    public JLabel getjLabelTCC()
    {
        return jLabelTCC;
    }

    public JLabel getjLabelWMC()
    {
        return jLabelWMC;
    }

    public JLabel getjLabelATFDAnal()
    {
        return jLabelATFDAnal;
    }

    public JLabel getjLabelTCCAnal()
    {
        return jLabelTCCAnal;
    }

    public JLabel getjLabelWMCAnal()
    {
        return jLabelWMCAnal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonOpen = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelClassName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelMethodCount = new javax.swing.JLabel();
        jLabelLinesCode = new javax.swing.JLabel();
        jLabelWMC = new javax.swing.JLabel();
        jLabelTCC = new javax.swing.JLabel();
        jLabelATFD = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabelWMCAnal = new javax.swing.JLabel();
        jLabelTCCAnal = new javax.swing.JLabel();
        jLabelATFDAnal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonOpen.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sebastien\\Ecole\\Git\\GenieLogiciel-LaboFinal\\src\\main\\resources\\open.png")); // NOI18N
        jButtonOpen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonOpenActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOpen);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabelClassName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelClassName.setForeground(new java.awt.Color(255, 0, 0));
        jLabelClassName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClassName.setText("Classe : ");
        jPanel2.add(jLabelClassName, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(5, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre de méthodes : ");
        jPanel4.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre de lignes de code :");
        jPanel4.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mesure de la complexité de la classe (WMC) :");
        jPanel4.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mesure de la cohésion d’une classe (TCC) :");
        jPanel4.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Indicateur du respect de l’encapsulation des autres classes (ATFD) :");
        jPanel4.add(jLabel6);

        jPanel3.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setMaximumSize(new java.awt.Dimension(40, 40));
        jPanel5.setMinimumSize(new java.awt.Dimension(18, 40));
        jPanel5.setPreferredSize(new java.awt.Dimension(18, 40));
        jPanel5.setLayout(new java.awt.GridLayout(5, 0));

        jLabelMethodCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMethodCount.setText("N/D");
        jPanel5.add(jLabelMethodCount);

        jLabelLinesCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLinesCode.setText("N/D");
        jPanel5.add(jLabelLinesCode);

        jLabelWMC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWMC.setText("N/D");
        jPanel5.add(jLabelWMC);

        jLabelTCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTCC.setText("N/D");
        jPanel5.add(jLabelTCC);

        jLabelATFD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelATFD.setText("N/D");
        jPanel5.add(jLabelATFD);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(5, 0));
        jPanel7.add(filler1);
        jPanel7.add(filler2);

        jLabelWMCAnal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWMCAnal.setText("<Analyse>");
        jPanel7.add(jLabelWMCAnal);

        jLabelTCCAnal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTCCAnal.setText("<Analyse>");
        jPanel7.add(jLabelTCCAnal);

        jLabelATFDAnal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelATFDAnal.setText("<Analyse>");
        jPanel7.add(jLabelATFDAnal);

        jPanel3.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenActionPerformed
        this.state = new LoadClassState();
        this.state.doAction(mediator);
        
        this.state = new ClassLoadedState();
        this.state.doAction(mediator);
    }//GEN-LAST:event_jButtonOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            new Gui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelATFD;
    private javax.swing.JLabel jLabelATFDAnal;
    private javax.swing.JLabel jLabelClassName;
    private javax.swing.JLabel jLabelLinesCode;
    private javax.swing.JLabel jLabelMethodCount;
    private javax.swing.JLabel jLabelTCC;
    private javax.swing.JLabel jLabelTCCAnal;
    private javax.swing.JLabel jLabelWMC;
    private javax.swing.JLabel jLabelWMCAnal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
